data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  env_name: 'Walker2d-v2'

train:
  reward_decay: 0.99

  surrogate_clip: True
  actor_update_steps: 10

  kl_loss_lam: 0.5
  kl_loss_eta: 50

  actor_train_episode: 10
  critic_train_episode: 10

  kl_lam_alpha: 2.0


  clip_epsilon: 0.2
  kl_target: 0.003
  kl_target_beta: 1.5

  actor_lr: 0.0001
  critic_lr: 0.0002

  save_checkpoints_steps: 2000
  model_dir: 'logs/ppo'
  max_steps: 20000