data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  env_name: 'Walker2d-v2'

train:
  reward_decay: 0.9

  entropy_beta: 0.01

  global_ep: 0


  update_n_iter: 5

  actor_lr: 0.0001
  critic_lr: 0.001

  save_checkpoints_steps: 1000000
  model_dir: 'logs/a3c'
  max_steps: 10000000