data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  env_name: 'Walker2d-v2'

train:
  reward_decay: 0.99

  dis_entropy_beta: 0.01
  con_entropy_beta: 0.0001

  update_n_iter: 5

  actor_learning_rate: 0.0001
  critic_learning_rate: 0.001

  save_checkpoints_steps: 500000
  model_dir: 'logs/a3c'
  max_steps: 2000000