data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  env_name: 'LunarLander-v2'

train:
  batch_size: 32
  max_episode_steps: 400

  initial_epsilon: 1.0
  epsilon_decrement: 0.0001
  final_epsilon: 0.01

  reward_decay: 0.99
  observe_n_iter: 100000
  memory_size: 100000
  replace_target_n_iter: 1000

  learning_rate: 0.001
  save_checkpoints_steps: 100000
  model_dir: 'logs/dueling-DQN'
  max_steps: 400000