data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  num_action: 11
  state_dim: 3

train:
  batch_size: 32

  initial_epsilon: 0.1

  reward_decay: 0.9
  observe_n_iter: 1500
  memory_size: 3000
  replace_target_n_iter: 200

  learning_rate: 0.005
  save_checkpoints_steps: 5000
  model_dir: 'logs/double-DQN'
  max_steps: 20000