data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  env_name: 'CartPole-v1'

train:
  reward_decay: 0.99

  learning_rate: 0.001
  save_checkpoints_steps: 100
  model_dir: 'logs/reinforce'
  max_steps: 1000