data:
  base_path: 'data/'
  save_state_file: 'state.pkl'
  env_name: 'MountainCar-v0'

train:
  reward_decay: 0.995

  learning_rate: 0.01
  save_checkpoints_steps: 100
  model_dir: 'logs/reinforce'
  max_steps: 1000